westmount <- read.csv("input/Westmount_Public.csv")

streets <- c("SAINT-SULPICE", "DE LAVIGNE", "")

PARKS <- c("JARDIN QUEEN ELIZABETH", "PARC ARGYLE", "PARC STAYNER", "PARC DORCHESTER CLARKE", "PARC KING GEORGE", "PARC WESTMOUNT")

westmount_parks <- subset(westmount, ROUTE.PARC== c("JARDIN QUEEN ELIZABETH", "PARC ARGYLE", "PARC STAYNER", "PARC DORCHESTER CLARKE", "PARC KING GEORGE", "PARC WESTMOUNT") )
